### PR TITLE
Version

### PR DESCRIPTION
**Pull request by OndrejSladky**
Version is now automatically updated after every single commit.

### CODE REVIEW

**Comment by karel-brinda** [comment]
Looks good, just the version of the hash is just a bit too long. I think 6 characters should be enough (already for this the prob of a collision should be very low).

btw. in the current implementation, which version will appear in "true" releases (I just remember this is what I was always struggling with a couple of ys ago)?

**Comment by OndrejSladky** [comment]
> btw. in the current implementation, which version will appear in "true" releases (I just remember this is what I was always struggling with a couple of ys ago)?

I'm not entirely sure what is the question.
But if it is which versions will have separate tag on gh, then I was thinking I'd make it every 0.x version.
Or do you have any other sugestions?

**Comment by karel-brinda** [comment]
When you release a New version, will it be something like 0.3 or
0.3-348a841 ? For the actual releases the version should be the former

**Comment by OndrejSladky** [comment]
The way it is now, it'll display 0.3-348a841.
If you think this is not good enough, i'll file another issue and will think about how to elegantly fix this.

**Comment by karel-brinda** [comment]
In case it's a new release, it should be just `0.3`. I'm not sure how it's doable, but it somehow should be as a I often see it in software packages.

**Comment by karel-brinda** [comment]
btw. see also `git describe --tags --always`

**Comment by karel-brinda** [comment]
Actually `$ git describe --abbrev=4 --dirty --always --tags v0.1.0` seems to be working really well!!!!! When it's a release, it prints just eg `v0.1.0`.

So it just needs to be included somehow in the Makefile – as the first step of compilation, this string should be generated.

One difficulty I see is that it make should be able to compile it even out of git without a failure.

**Pull request merged**
